package net.grandcentrix.api.uwb.model

import androidx.core.uwb.RangingParameters
import androidx.core.uwb.UwbComplexChannel
import androidx.core.uwb.UwbDevice
import kotlin.random.Random

/**
 * RangingConfig is a data class that encapsulates parameters for configuring the Ultra-Wideband (UWB) device
 * to start ranging.
 *
 * @property uwbConfigType The type of UWB configuration. Defaults to [RangingParameters.CONFIG_UNICAST_DS_TWR].
 * @property sessionId The session ID. Defaults to a random integer value generated by [Random.Default.nextInt].
 * @property subSessionId The sub-session ID. Defaults to 0.
 * @property sessionKey The session key. Defaults to null.
 * @property subSessionKey The sub-session key. Defaults to null.
 * @property channel The UWB channel to be used for ranging, part of [UwbComplexChannel]. Defaults to 9.
 * @property preambleIndex The preamble index, part of [UwbComplexChannel]. Defaults to 10.
 * @property updateRateType The update rate type for ranging. Defaults to [RangingParameters.RANGING_UPDATE_RATE_FREQUENT].
 */

class RangingConfig(
    val uwbConfigType: Int = RangingParameters.CONFIG_UNICAST_DS_TWR,
    val sessionId: Int = Random.Default.nextInt(),
    val subSessionId: Int = 0,
    val sessionKey: ByteArray? = null,
    val subSessionKey: ByteArray? = null,
    val channel: Int = 9,
    val preambleIndex: Int = 10,
    val updateRateType: Int = RangingParameters.RANGING_UPDATE_RATE_FREQUENT
)

/**
 * Converts the current [RangingConfig] instance into [RangingParameters] needed to configure
 * ranging operations with Ultra-Wideband (UWB) devices.
 *
 * @param uwbDevices List of [UwbDevice] objects representing peer devices involved in ranging.
 * @return A new instance of [RangingParameters] configured based on the properties of this [RangingConfig].
 */
fun RangingConfig.toRangingParameters(uwbDevices: List<UwbDevice>): RangingParameters =
    RangingParameters(
        uwbConfigType = uwbConfigType,
        sessionId = sessionId,
        sessionKeyInfo = sessionKey,
        complexChannel = UwbComplexChannel(channel = channel, preambleIndex = preambleIndex),
        peerDevices = uwbDevices,
        updateRateType = updateRateType,
        subSessionId = subSessionId,
        subSessionKeyInfo = subSessionKey
    )
